//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Test1
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Заказ.
    /// </summary>
    // *** Start programmer edit section *** (Заказ CustomAttributes)

    // *** End programmer edit section *** (Заказ CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗаказE", new string[] {
            "КодЗаказа as \'Код заказа\'",
            "Дата as \'Дата\'",
            "Контрагент as \'Контрагент\'",
            "Контрагент.ФИО as \'ФИО\'",
            "Сотрудник as \'Сотрудник\'",
            "Сотрудник.ФИО as \'ФИО\'"}, Hidden=new string[] {
            "Контрагент.ФИО",
            "Сотрудник.ФИО"})]
    [MasterViewDefineAttribute("ЗаказE", "Контрагент", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [MasterViewDefineAttribute("ЗаказE", "Сотрудник", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [View("ЗаказL", new string[] {
            "КодЗаказа as \'Код заказа\'",
            "Дата as \'Дата\'",
            "Контрагент.ФИО as \'ФИО\'",
            "Сотрудник.ФИО as \'ФИО\'"})]
    public class Заказ : ICSSoft.STORMNET.DataObject
    {
        
        private int fКодЗаказа;
        
        private System.DateTime fДата;
        
        private IIS.Test1.Контрагент fКонтрагент;
        
        private IIS.Test1.Сотрудник fСотрудник;
        
        // *** Start programmer edit section *** (Заказ CustomMembers)

        // *** End programmer edit section *** (Заказ CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.Дата CustomAttributes)

        // *** End programmer edit section *** (Заказ.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.Дата Get start)

                // *** End programmer edit section *** (Заказ.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (Заказ.Дата Get end)

                // *** End programmer edit section *** (Заказ.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.Дата Set start)

                // *** End programmer edit section *** (Заказ.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (Заказ.Дата Set end)

                // *** End programmer edit section *** (Заказ.Дата Set end)
            }
        }
        
        /// <summary>
        /// КодЗаказа.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.КодЗаказа CustomAttributes)

        // *** End programmer edit section *** (Заказ.КодЗаказа CustomAttributes)
        public virtual int КодЗаказа
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.КодЗаказа Get start)

                // *** End programmer edit section *** (Заказ.КодЗаказа Get start)
                int result = this.fКодЗаказа;
                // *** Start programmer edit section *** (Заказ.КодЗаказа Get end)

                // *** End programmer edit section *** (Заказ.КодЗаказа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.КодЗаказа Set start)

                // *** End programmer edit section *** (Заказ.КодЗаказа Set start)
                this.fКодЗаказа = value;
                // *** Start programmer edit section *** (Заказ.КодЗаказа Set end)

                // *** End programmer edit section *** (Заказ.КодЗаказа Set end)
            }
        }
        
        /// <summary>
        /// Заказ.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.Контрагент CustomAttributes)

        // *** End programmer edit section *** (Заказ.Контрагент CustomAttributes)
        [PropertyStorage(new string[] {
                "Контрагент"})]
        [NotNull()]
        public virtual IIS.Test1.Контрагент Контрагент
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.Контрагент Get start)

                // *** End programmer edit section *** (Заказ.Контрагент Get start)
                IIS.Test1.Контрагент result = this.fКонтрагент;
                // *** Start programmer edit section *** (Заказ.Контрагент Get end)

                // *** End programmer edit section *** (Заказ.Контрагент Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.Контрагент Set start)

                // *** End programmer edit section *** (Заказ.Контрагент Set start)
                this.fКонтрагент = value;
                // *** Start programmer edit section *** (Заказ.Контрагент Set end)

                // *** End programmer edit section *** (Заказ.Контрагент Set end)
            }
        }
        
        /// <summary>
        /// Заказ.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.Сотрудник CustomAttributes)

        // *** End programmer edit section *** (Заказ.Сотрудник CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудник"})]
        [NotNull()]
        public virtual IIS.Test1.Сотрудник Сотрудник
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.Сотрудник Get start)

                // *** End programmer edit section *** (Заказ.Сотрудник Get start)
                IIS.Test1.Сотрудник result = this.fСотрудник;
                // *** Start programmer edit section *** (Заказ.Сотрудник Get end)

                // *** End programmer edit section *** (Заказ.Сотрудник Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.Сотрудник Set start)

                // *** End programmer edit section *** (Заказ.Сотрудник Set start)
                this.fСотрудник = value;
                // *** Start programmer edit section *** (Заказ.Сотрудник Set end)

                // *** End programmer edit section *** (Заказ.Сотрудник Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗаказE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаказE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаказE", typeof(IIS.Test1.Заказ));
                }
            }
            
            /// <summary>
            /// "ЗаказL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаказL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаказL", typeof(IIS.Test1.Заказ));
                }
            }
        }
    }
}
